### ISSUE TITLE
Does this work in Windows?

### ISSUE THREAD

**Issue by robross0606** [nodesource/nsolid-npm#21]
When attempting to run `npm install -g nsolid` in Windows, I get this error:
```
C:\Users\user\AppData\Local\Volta\tmp\image\packages\.tmpDlHyyr\nsolid -> C:\Users\user\AppData\Local\Volta\tmp\image\packages\.tmpDlHyyr\node_modules\nsolid\index.js

> nsolid@1.0.2 postinstall C:\Users\user\AppData\Local\Volta\tmp\image\packages\.tmpDlHyyr\node_modules\nsolid
> ./lib/runtime.js

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nsolid@1.0.2 postinstall: `./lib/runtime.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nsolid@1.0.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2024-09-06T12_20_57_148Z-debug.log
```

Typically, when I see something like "'.' is not recognized as an internal or external command" that's a pretty good indication this is designed for a Unix shell environment and not Windows.

**Comment by edsadr** [comment]
Thanks for your report, however, to use N|Solid from NPM is not designed to work like this, you would need to use it as a dependency as explained here:  https://github.com/nodesource/nsolid-npm?tab=readme-ov-file#usage or install N|Solid for windows downloading it from https://downloads.nodesource.com/
